### ISSUE TITLE
Maybe: Inconsistent phases TypeError masked by __repr__ AttributeError 

### ISSUE THREAD

**Issue by nealtodd** [FactoryBoy/factory_boy#630]
#### Description
The TypeError check in `declarations.Maybe.__init__` is masked by an AttributeError because the TypeError error message uses `__repr__` which in turn uses `self` attributes that haven't yet be set in `__init__`.

#### To Reproduce
Noticed when upgrading from `2.8.1` to `2.12.0` on a factory that used Traits and had a PostGeneration hook which resulted in a Maybe object with a yes declaration evaluating to a List object (`attributes` enum) and a no declaration evaluating to a PostGeneration object (`post_instance` enum).

To reproduce: Create a `Maybe` object with yes/no declarations with differing enums. 

##### Model / Factory code
Minimal example

```python
In [1]: from factory.declarations import LazyAttribute, Maybe, PostGenerationDeclaration

In [2]: Maybe(None, LazyAttribute(None), PostGenerationDeclaration())

AttributeError                            Traceback (most recent call last)
----> 1 Maybe(None, LazyAttribute(None), PostGenerationDeclaration())

~/venv/lib/python3.6/site-packages/factory/declarations.py in __init__(self, decider, yes_declaration, no_declaration)
    456
    457         if len(used_phases) > 1:
--> 458             raise TypeError("Inconsistent phases for %r: %r" % (self, phases))
    459
    460         self.FACTORY_BUILDER_PHASE = used_phases.pop() if used_phases else enums.BuilderPhase.ATTRIBUTE_RESOLUTION

~/venv/lib/python3.6/site-packages/factory/declarations.py in __repr__(self)
    504
    505     def __repr__(self):
--> 506         return 'Maybe(%r, yes=%r, no=%r)' % (self.decider, self.yes, self.no)
    507
    508

AttributeError: 'Maybe' object has no attribute 'decider'
```

##### The issue
The TypeError error message uses `self` but the `__repr__` uses attributes that only get set on `self` at the end of `__init__`. This raises an AttributeError which masks the actual TypeError.

If the attributes were set ahead of the check on https://github.com/FactoryBoy/factory_boy/blob/master/factory/declarations.py#L454 then the expected exception would be raised:

```python
In [1]: from factory.declarations import LazyAttribute, Maybe, PostGenerationDeclaration

In [2]: Maybe(None, LazyAttribute(None), PostGenerationDeclaration())

TypeError                                 Traceback (most recent call last)
/vagrant/.konchrc in <module>
----> 1 Maybe(None, LazyAttribute(None), PostGenerationDeclaration())

~/venv/lib/python3.6/site-packages/factory/declarations.py in __init__(self, decider, yes_declaration, no_declaration)
    460
    461         if len(used_phases) > 1:
--> 462             raise TypeError("Inconsistent phases for %r: %r" % (self, phases))
    463
    464         self.FACTORY_BUILDER_PHASE = used_phases.pop() if used_phases else enums.BuilderPhase.ATTRIBUTE_RESOLUTION

TypeError: Inconsistent phases for Maybe(None, yes=<factory.declarations.LazyAttribute object at 0x7f0ec15d4d30>, no=<factory.declarations.PostGenerationDeclaration object at 0x7f0ec15d4160>): {'yes_declaration': 'attributes', 'no_declaration': 'post_instance'}
```

#### Notes

Check was introduced in 33d27c219044

**Comment by federicobond** [comment]
Hi @nealtodd, thanks for your report. I have submitted a fix for your issue, ideally we will be able to include it in the next release.

**Comment by nealtodd** [comment]
Excellent, thanks @federicobond for the speedy fix.
