### ISSUE TITLE
_add_items() got an unexpected keyword argument 'through_defaults' after updated Django to 2.2.1

### ISSUE THREAD

**Issue by Vokler** [FactoryBoy/factory_boy#607]
#### Description
*TypeError: _add_items() got an unexpected keyword argument 'through_defaults' after upgraded Django to 2.2.1*

#### To Reproduce
*Many-To-Many relation - issue happens after adding new elements to object.*

##### Model / Factory code
```python
class CourseModule(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='modules')
    name = models.CharField(max_length=250, null=True, blank=True)
    lectures = SortedManyToManyField(Lecture, blank=True, related_name='modules')
    sort_value = models.PositiveIntegerField(default=0)
    is_on_sale = models.BooleanField(default=False)

class CourseModuleFactory(factory.DjangoModelFactory):
    name = factory.Sequence(lambda n: 'Test Course Module %s' % n)
    course = factory.SubFactory(CourseFactory)

    class Meta:
        model = models.CourseModule

    @factory.post_generation
    def lectures(self, create, extracted, **kwargs):
        if create and extracted:
            for extract in extracted:
                self.lectures.add(extract)
```

##### The issue
*Add a short description along with your code*

```python
Error
Traceback (most recent call last):
  File "/Users/vokler/projects/ca/ca-server/lectures/tests/test_course.py", line 80, in test_replace_from_parent
    course_module = CourseModuleFactory(course=course, lectures=lectures)
  File "/Users/vokler/projects/ca/venv/lib/python3.6/site-packages/factory/base.py", line 46, in __call__
    return cls.create(**kwargs)
  File "/Users/vokler/projects/ca/venv/lib/python3.6/site-packages/factory/base.py", line 564, in create
    return cls._generate(enums.CREATE_STRATEGY, kwargs)
  File "/Users/vokler/projects/ca/venv/lib/python3.6/site-packages/factory/django.py", line 141, in _generate
    return super(DjangoModelFactory, cls)._generate(strategy, params)
  File "/Users/vokler/projects/ca/venv/lib/python3.6/site-packages/factory/base.py", line 501, in _generate
    return step.build()
  File "/Users/vokler/projects/ca/venv/lib/python3.6/site-packages/factory/builder.py", line 299, in build
    context=postgen_context,
  File "/Users/vokler/projects/ca/venv/lib/python3.6/site-packages/factory/declarations.py", line 623, in call
    instance, create, context.value, **context.extra)
  File "/Users/vokler/projects/ca/ca-server/lectures/factories.py", line 118, in lectures
    self.lectures.add(extract, through_defaults=None)
  File "/Users/vokler/projects/ca/venv/lib/python3.6/site-packages/django/db/models/fields/related_descriptors.py", line 938, in add
    through_defaults=through_defaults,
TypeError: _add_items() got an unexpected keyword argument 'through_defaults'
```

#### Notes
*I'm not sure that this issue belongs factory boy, but after researching bug I don't have idea*
