### ISSUE TITLE
TypeError: generate() missing 1 required positional argument: 'params'

### ISSUE THREAD

**Issue by jaap3** [FactoryBoy/factory_boy#787]
After upgrading from 3.0.1 to 3.1 I suddenly get a `TypeError: generate() missing 1 required positional argument: 'params'`.

I have a `factory.LazyAttribute` that calls `factory.Faker('safe_email').generate()` conditionally. This worked before and now raises a `TypeError`.

This seems to be caused by commit f0a4ef008f07f8d42221565d8c33b88083f0be6d. Would it be possible to make `params` optional?

**Comment by rbarrois** [comment]
Hi! Thanks for the report.

The `factory.Faker.generate` is a private API; its direct use is not supported.

I'm a bit surprised by your issue though, the API is supposed to be `foo = factory.Faker('safe_email')`, not `foo = factory.LazyAttribute(lambda o: factory.Faker('safe_email').generate())` — the former is much shorter ;)

**Comment by jaap3** [comment]
Sorry, I was in a hurry when I wrote this bug report. The full code is something like this:

```
emails = factory.LazyAttribute(lambda o: [factory.Faker('safe_email').generate()] if o.some_boolean_field else [])
```

I'm not sure why it's written like this (I'm not the author of that bit of code).

**Comment by rbarrois** [comment]
I see ;)

The "proper" way would be:
```python
emails = factory.Maybe(
    factory.SelfAttribute('some_boolean_field'),
    factory.List([factory.Faker('safe_email')]),
    [],
)
```

I guess we should make it easier to find in the docs; and maybe easier to write too…

However, there seems to be a bug deeper down (see #786) in the Faker code which might fix the code you've got.

**Comment by jaap3** [comment]
Thanks for the snippet of the "proper" way. I'll update our code so we don't use a private API anymore.

I don't think there's anything to do on the factory_boy side, so I'll close this issue. Thanks again!
